Fixes encoding problem on python3
Traceback (most recent call last):
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 562, in <module>
    Main()
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 554, in Main
    test_suite.Run(options.command, args,
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 467, in Run
    cases = self.EnumerateTests(tests)
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 399, in EnumerateTests
    strict_case = TestCase(self, name, full_path, True)
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 214, in __init__
    self.contents = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbd in position 217: illegal multibyte sequence

Traceback (most recent call last):
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 562, in <module>
    Main()
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 554, in Main
    test_suite.Run(options.command, args,
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 488, in Run
    result = case.Run(command_template)
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 301, in Run
    result = self.RunTestIn(command_template, tmp)
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 290, in RunTestIn
    tmp.Write(self.GetSource())
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 251, in GetSource
    self.suite.GetInclude("testIntl.js") + \
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 369, in GetInclude
    contents = stripHeader(f.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 33422: illegal multibyte sequence

Traceback (most recent call last):
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 562, in <module>
    Main()
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 554, in Main
    test_suite.Run(options.command, args,
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 488, in Run
    result = case.Run(command_template)
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 301, in Run
    result = self.RunTestIn(command_template, tmp)
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 290, in RunTestIn
    tmp.Write(self.GetSource())
  File "C:\work\study\languages\typescript\jerryscript\tests\test262\es51\tools\packaging\test262.py", line 112, in Write
    os.write(self.fd, str)
TypeError: a bytes-like object is required, not 'str'

Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>